### ISSUE TITLE
Style guide todo

### ISSUE THREAD

**Issue by rovolution** [socialtables/socialtables.github.io#3]
- [x] add section about float (and treat it as a positional property)
- [x] add in responsive-utils to vendor files in tree structure
- [x] examples for all rules
- [x] add section about width, height, max/min width height (and treat it as a box-model property)
- [x] add SASS syntax for variables and scoping variables within styles
- [x] add section about responsive utils
- [ ] fix SASS mixin syntax
- [ ] add rule for SASS placeholder vs mixin: http://www.sitepoint.com/sass-mixin-placeholder/
- [ ] create repo with pre-built assets and add links to style guide
